routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/create-symlink', function () {
    Artisan::call('storage:link');
});

Route::get('/migratefresh', function () {
    Artisan::call('migrate:fresh');
});

Route::get('/seeder', function(){
    Artisan::call('db:seed');
});

Route::get('/down', function(){
    Artisan::call('down');
});

// Route::get('/up', function(){
//     Artisan::call('up');
// });


Auth::routes();

Route::prefix('admin')->middleware('auth')->group(function(){
    //You must be logged in to access this route
    Route::get('/index', 'AdminController@index')->name('admin.index');

    Route::resource('pages', 'PageController');

    Route::resource('categories', 'CategoryController');

    Route::resource('slides', 'SlideController');

    Route::resource('posts', 'PostController');
    
    Route::resource('menus', 'MenuController');

    Route::resource('comments', 'CommentController', ['except'=>['store']]);

    Route::resource('users', 'UserController');

    Route::get('users/profile/{user}', 'UserController@profile')->name('users.profile');

    Route::patch('users/profile/{user}', 'UserController@updateProfile')->name('users.updateProfile');

    Route::get('users/password/{user}', 'UserController@changePassword')->name('users.changePassword');

    Route::patch('users/password/{user}', 'UserController@postChangePassword')->name('users.postChangePassword');

    Route::patch('comments/approve/{comment}', 'CommentController@approve')->name('comments.approve');

    Route::patch('comments/disapprove/{comment}', 'CommentController@disapprove')->name('comments.disapprove');
    
    Route::resource('postviews', 'PostViewController');

    Route::delete('postviews-deleteall', 'PostViewController@deleteall')->name('postviews.deleteall');
    
    Route::resource('settings', 'SettingController');

    Route::resource('contactus', 'ContactUsController');

    Route::get('contactus/{contactus}/reply', 'ContactUsController@reply')->name('contactus.reply');

    Route::post('message/send', 'ChatController@send');
    
});

Route::post('comments/store', 'CommentController@store')->name('comments.store');
Route::post('comments/reply', 'CommentController@reply')->name('comments.reply');

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'FrontendController@index')->name('frontend.index');
// Route::get('/page/{menu}/', 'FrontendController@urlmapper')->name('frontend.urlmapper');
Route::get('{menuslug}', 'FrontendController@urlmapper')->name('frontend.urlmapper');

Route::get('posts/{slug}', 'FrontendController@showpost')->name('frontend.posts.show');

Route::get('posts/category/{slug}', 'FrontendController@showcategoryposts')->name('frontend.category.posts');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Post extends Model
{
    //
    use Sluggable;

    protected $fillable = ['user_id', 'title', 'seo_description', 'content', 'featured_image', 'category_id', 'comment_status', 'status', 'visibility', 'slug', 'updated_by'];

    public function user(){
        return $this->belongsTo('App\User');
    }

    public function categories(){
        return $this->belongsToMany('App\Category');
    }

    public function tags(){
        return $this->belongsToMany('App\Tag');
    }

    public function comments(){
        return $this->hasMany('App\Comment')->whereNull('parent_id');
    }

    public function tagLists(){
        return $this->tags->pluck('id')->all();
    }

    public function postViews(){
        return $this->hasMany('App\PostView');
    }

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    //I also want to link to posts using a unique 'slug' rather than the default ID in the URL.
    // public function getRouteKeyName()
    // {
    //     return 'slug';
    // }
}

app/PostView.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Auth;
use Stevebauman\Location\Facades\Location;
// use Illuminate\Http\Request;

class PostView extends Model
{
    //
    protected $fillable = ['post_id', 'session_id', 'user_id', 'ip', 'country', 'city', 'agent'];

    public static function createViewLog($post){
        $postView = new PostView;
        $postView->post_id = $post->id;
        $postView->session_id = \Request::getSession()->getId();
        $postView->user_id = (Auth::check()) ? Auth::id() : null; //No need to use Auth()->user()->id as we have an inbuilt function to get auth id.
        $postView->ip = \Request::getClientIp();
        $postView->country = Location::get($postView->ip)==null ? NULL : Location::get($postView->ip)->countryName;
        $postView->city = Location::get($postView->ip)==null ? NULL : Location::get($postView->ip)->cityName;
        $postView->agent = \Request::header('User-Agent');
        $postView->save();
    }

    public function post(){
        return $this->belongsTo('App\Post');
    }

    public function user(){
        return $this->belongsTo('App\User');
    }

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\Category;
use App\Tag;
use App\Setting;
use Illuminate\Support\Facades\Storage;
use Auth;

class PostController extends Controller
{
    // public function __construct(){
    //     $this->middleware('auth', ['except'=>['show']]);
    // }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::orderBy('updated_at', 'desc')->get();

        //dd($posts);

        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::orderBy('name')->get();
        return view('posts.create', compact('categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->file('featured_image'));
        //validate
        $this->validate(request(), [
            'title'=>'required|min:3',
            'content' => 'required',
            'featured_image'=>'mimes:jpg,png,jpeg',
        ]);

        $post = Post::create([
            'user_id' => Auth::user()->id,
            'title' => $request->title,
            'seo_description' => $request->seo_description,
            'content' => $request->content,
            //'featured_image' => $request->file('featured_image')==null? null :$request->file('featured_image')->storeAs('post_images//', uniqid().'.jpg', 'public'),
            'comment_status' => $request->comment_status,
            'status' => $request->status,
            'visibility' => $request->visibility,
            'updated_by' => Auth::user()->id,
        ]);

        //I set the 'featured_image' column in the database to a default of "post_images/default-post-image.jpg"
        if ($request->hasFile('featured_image')) {
            $post->update([
                'featured_image' => $request->file('featured_image')->storeAs('post_images//', uniqid().'.jpg', 'public'),
            ]);    
        }

        //If there are tags coming from the frontend, otherwise, it will throw an...
        //error trying to call foreach on an empty array.
        if ($request->tags) {
            //dd($request->tags) is in this order:
            //array:3 [▼
            //  0 => "3"     ---> exist
            //  1 => "2"     ---> exist
            //  2 => "Mental Wellbeing"   ---> does not exist
            // ]
            //For each tag, create it in the "tags" table.
            foreach ($request->tags as $tagId) {
                //Check if the tag exists.
                //NB: If the tag doesn't exist, the tagId will be the name of the tag.
                if (Tag::find($tagId)==null) {
                    // If it does not exist, create a new tag with the tag name.
                    //In this case, the tagId will be the tag name.
                    $tag = Tag::create([
                        'name' => $tagId,
                    ]);
                    
                    // Attach it
                    $post->tags()->attach($tag->id);
                }else{

                    //Just attach the tag id you got.
                    $post->tags()->attach($tagId);
                }

            }
        }

        $post->categories()->attach($request->categoryids);

        return redirect()->route('posts.index')->with('success', 'Post created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('posts.show', compact('post'));
        //$themename = Setting::find(1)->themename;
        //I had to use double quotes because of the variable name.
        //return view("frontend.themes.$themename.single-post", compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $tags = Tag::orderBy('name')->get();
        return view('posts.edit', compact('post', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        // dd($request->file('featured_image'));
        // dd($post->featured_image);
        //validate
        $this->validate(request(), [
            'title'=>'required|min:3',
            'content' => 'required',
            'featured_image'=>'mimes:jpg,png,jpeg',
        ]);

        if ($request->file('featured_image')!=null) {
            //Delete the former image.
            Storage::disk('public')->delete($post->featured_image);
        }

        $post->update([
            'title' => $request->title,
            'seo_description' => $request->seo_description,
            'content' => $request->content,
            'featured_image' => $request->file('featured_image')==null? $post->featured_image : $request->file('featured_image')->storeAs('post_images/', uniqid().'.jpg', 'public'),
            'comment_status' => $request->comment_status,
            'status' => $request->status,
            'visibility' => $request->visibility,
            'updated_by' => Auth::user()->id,
            'slug' => null, //This makes the slug to automatically update with the title. If you don't want the slug to be auto-updated, comment it out.
        ]);


        //If there are tags coming from the frontend, otherwise, it will throw an...
        //error trying to call foreach on an empty array.
        if ($request->tags) {
            //dd($request->tags); //is in this order:
            //array:3 [▼
            //  0 => "3"     ---> exist
            //  1 => "2"     ---> exist
            //  2 => "Mental Wellbeing"   ---> does not exist
            // ]

            //Now, first of all, create an array to store tag Ids.
            $tagIds = [];

            //For each tag
            foreach ($request->tags as $tagId ) {
                //Find out if the tag exists.
                //NB: If the tag doesn't exist, the tagId will be the name of the tag.
                if (Tag::find($tagId)==null) {
                    //Create the tag
                    $tag = Tag::create([
                        'name' => $tagId,
                    ]);
                    
                    //Add the newly generated id to an array of tag ids.
                    $tagIds[] =  $tag->id;
            
                }else{
                    //Else, if the tag exists, just add the existing Id to the array of tag Ids.
                    
                    $tagIds[] = $tagId;
                }
            }
            
            //At the end of the day, sync all of them at once.
            $post->tags()->sync($tagIds);

            //If I had done it with the way I approached it in the store() method above,
            //the sync method will be executed for each tag Id in the loop.
            //At the end of the day, it is only the last tag id that stays in the database
            //Why? because the sync() method has the ability to delete.
        }else{
            //If there are no tags from the frontend, delete or detach all existing tags.
            
            
            //First of all check if there are tags related to this post otherwise, it will ...
            //throw an error when trying to call detach on a post without tags.
            if ($post->tags) {
                //Then detach all tags
                $post->tags()->detach();
            }
        }
        
        $post->categories()->sync($request->categoryids);

        return redirect()->route('posts.index')->with('success', 'Post updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        //Delete the image 
        Storage::disk('public')->delete($post->image);

        $post->categories()->detach();

        $post->delete();

        return redirect()->route('posts.index')->with('success', 'Post deleted successfully');
    }
}

resources/views/posts/create.blade.php
@extends('layouts.dashboard')

@section('styles')
    <link href="{{asset('summernote/dist/summernote.css')}}" rel="stylesheet">
@endsection

@section('content')
    @include('partials.errorbag')
    @include('partials.successmsg')

    <section class="content-header">
        <h1>Add New Post</h1>
    </section>

    {{-- Main content --}}
    <section class="content">
        <form action="{{ route('posts.store') }}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-md-8">
                    <div class="form-group">
                        <label for="">Post Title</label>
                        <input type="text" name="title" id="" class="form-control" required placeholder="Post Title">
                    </div>
                    <div class="form-group">
                        <label for="">SEO Description (optional)</label>
                        <input type="text" name="seo_description" id="" class="form-control" placeholder="SEO Description (optional)">
                    </div>
                    <div class="form-group">
                        <label for="">Post Content</label>
                        <textarea name="content" class="summernote" id="summernote"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="">Post Tags</label>
                        <select name="tags[]" class="form-control select2"  multiple>
                            @foreach ($tags as $tag)
                                <option value="{{ $tag->id }}">{{ $tag->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    
                </div>

                {{-- Second column --}}
                <div class="col-md-4">
                    <div class="box box-info">
                        <div class="box-header">
                            <h4>Post Attributes</h4>
                        </div>

                        <div class="box-body">
                            <div class="form-group">
                                <label for="">Featured Image</label>
                                <input type="file" name="featured_image">
                            </div>
                            <div class="form-group" id="vue-area">
                                <label for="">Categories</label>
                                <div style="border:1px solid #a9a9a9; width:100%; padding: 2%; height: 200px; overflow-y: scroll">
                                    {{-- <input type="hidden" value="0" name="categoryids[]"> <!--Just in case user does not select any category--> --}}
                                    <template v-for="category in categories">
                                        <input type="checkbox" name="categoryids[]" v-bind:value="category.id"> @{{category.name}} <br>
                                    </template>
                                </div>
                                
                                <h5 v-on:click="ok = !ok" style="cursor: pointer; color:#00a65a;"><i class="fa fa-plus"></i> Add new category</h5>
                                
                                <div v-show="ok">
                                    <div class="form-group" :class="{'has-error': hasError}">
                                        <input type="text" v-model="category_name" class="form-control" placeholder="Category Name" ref="newcategory_textbox">
                                    </div>
        
                                    <div class="form-group">
                                        <label for="">Parent Category</label>
                                        <select name="parent_category" id="" class="form-control" v-model="parent_category">
                                            <option value="0" selected>None</option>
                                            <option :value="category.id" v-for="category in categories">@{{category.name}}</option>
                                        </select>
                                    </div>
        
                                    <div class="form-group">
                                        <button type="button" class="btn btn-default" v-on:click="savecategory" :disabled="button_disabled">Add new category</button>
                                    </div>
                                    <small class="label bg-green" v-if="successmsg">Category created successfully</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="">Comment Status</label>
                                <input type="radio" name="comment_status" value="open" checked> Open &nbsp;
                                <input type="radio" name="comment_status" value="closed"> Closed
                            </div>
                        </div>
                    </div>


                    <div class="box box-info">
                        <div class="box-header">
                            <h4>Publish</h4>
                        </div>

                        <div class="box-body">
                            <div class="form-group">
                                <button class="btn btn-default">Save Draft</button>
                                <button class="btn btn-default pull-right">Preview</button>
                            </div>
                            <br>

                            <div class="form-group">
                                <i class="fa fa-info-circle"></i> <label for="">Status: </label>
                                <select name="status" id="" class="form-control">
                                    <option value="draft">Draft</option>
                                    <option value="published" selected>Published</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <i class="fa fa-eye"></i> <label for="">Visibility: </label>
                                <select name="visibility" id="" class="form-control">
                                    <option value="private">Private</option>
                                    <option value="public">Public</option>
                                    <option value="published" selected>Published</option>
                                </select>
                            </div>
                        </div>
                        
                        <div class="box-footer">
                            <div class="form-group">
                                <button type="submit" class="btn btn-info pull-right">Publish</button>
                            </div>
                        </div>
                    </div>

                </div>
            </div>      
        </form>
    </section>
@endsection

@section('scripts')
    <script src="{{asset('summernote/dist/summernote.js')}}"></script>
    <script src="{{asset('js/moment.js')}}"></script>

    <script>
        $(document).ready(function() {
            $('#summernote').summernote({
                height:450,
                placeholder: 'Post content'
            });
        });
    </script>

    <script>
        $('.select2').select2({
            placeholder: 'Select a tag',
            tags: true,
        });
    </script>

    <script>
        new Vue({
            el: '#vue-area',
            data: {
                categories: [],
                ok:false,
                category_name: '',
                parent_category: 0,
                button_disabled:false,
                hasError: false,
                successmsg: false,
            },
            methods:{
                savecategory(){
                    this.successmsg = false;
                    if (this.category_name!='') {
                        this.button_disabled=true,
                        this.hasError=false;
                        axios.post("{{url('api/category/create')}}", {
                            newcategory: this.category_name,
                            parent_category: this.parent_category,
                        })
                        .then(response=>{
                            console.log(response.data);
                            this.button_disabled=false;
                            this.category_name='';
                            this.successmsg = true;
                            this.getcategories();
                        });
                    }else{
                        this.$refs.newcategory_textbox.focus();
                        this.hasError=true;
                    }
                },
                getcategories(){
                    axios.get("{{url('api/categories')}}")
                    .then(response=>{
                        console.log(response.data);
                        this.categories = response.data;
                    });
                },
            },
            mounted: function() {
                this.getcategories();
            }
        });
    </script>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.dashboard')

@section('styles')
    @include('partials.datatableStyles')
@endsection

@section('content')
    @include('partials.successmsg')
    <section class="content-header">
        <h1>Posts <a href="{{route('posts.create')}}" class="btn btn-info">Add New</a></h1> 
    </section>

    {{-- Main content --}}
    <section class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="table-responsive">
                    <table id="example1" class="table table-bordered table-striped table-responsive">
                        <thead>
                            <tr>
                                <th><input type="checkbox" name="" id=""></th>
                                <th>Featured Image</th>
                                <th>Title</th>
                                <th><i class="ion ion-ios-eye"></i></th>
                                <th>Author</th>
                                <th>Categories</th>
                                <th>Status</th>
                                <th>Published</th>
                                <th>Updated At</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($posts as $post)
                                <tr>
                                    <td><input type="checkbox" name="" id=""></td>
                                    <td>
                                        {{-- @if(Storage::disk('public')->exists($post->featured_image)) --}}
                                            <img src="{{asset('storage/'.$post->featured_image)}}" class="img-rounded" alt="Post image" width="100">
                                        {{-- @else
                                            <img src="{{asset('storage/post_images/default-post-image.jpg')}}" class="img-rounded" alt="Post image"  width="100px" />
                                        @endif --}}
                                    </td>
                                    <td>
                                        <a href="{{ route('posts.edit', $post->id) }}">{{ $post->title }}</a> 
                                    </td>
                                    <td>{{ $post->postViews()->count() }}</td>
                                    <td>{{ $post->user->firstname ?? $post->user->username }} {{ $post->user->lastname }}</td>
                                    <td> 
                                        @foreach($post->categories as $postcategories) 
                                            - {{ $postcategories->name.' ' }}<br>
                                        @endforeach
                                    </td>
                                    <td>{{ ucfirst($post->status) }}</td>
                                    <td>Published {{ $post->created_at->format('j F, Y h:iA') }}</td> <!-- Different date format - diffForHumans('j F, Y')-->
                                    <td>Updated at {{ $post->updated_at->format('j F, Y h:iA') }}</td> <!-- Different date format - diffForHumans('j F, Y')-->
                                    <td>
                                        <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-success"><i class="fa fa-pencil"></i></a>
                                    </td>
                                    <td>
                                        <form id="deleteForm" method="post" action="{{ route('posts.destroy', $post->id) }}">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger" onClick='return confirm("Are you sure you want to delete?")'><i class="fa fa-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('scripts')
    @include('partials.datatableScripts')
@endsection

resources/views/posts/show.blade.php
@extends('layouts.dashboard')

@section('content')
    <section class="content-header">
        <h1>View Post <a href="{{route('posts.edit', $post->id)}}" class="btn btn-info">Edit</a></h1>
    </section>

    {{-- Main content --}}
    <section class="content">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">{{ $post->title }}</h3>
            </div>
            <div class="box-body" style="text-align: justify;">
                {!! $post->content !!}
            </div>
        </div>
    </section>
@endsection