routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/create-symlink', function () {
    Artisan::call('storage:link');
});

Route::get('/migratefresh', function () {
    Artisan::call('migrate:fresh');
});

Route::get('/seeder', function(){
    Artisan::call('db:seed');
});

Route::get('/down', function(){
    Artisan::call('down');
});

// Route::get('/up', function(){
//     Artisan::call('up');
// });


Auth::routes();

Route::prefix('admin')->middleware('auth')->group(function(){
    //You must be logged in to access this route
    Route::get('/index', 'AdminController@index')->name('admin.index');

    Route::resource('pages', 'PageController');

    Route::resource('categories', 'CategoryController');

    Route::resource('slides', 'SlideController');

    Route::resource('posts', 'PostController');
    
    Route::resource('menus', 'MenuController');

    Route::resource('comments', 'CommentController', ['except'=>['store']]);

    Route::resource('users', 'UserController');

    Route::get('users/profile/{user}', 'UserController@profile')->name('users.profile');

    Route::patch('users/profile/{user}', 'UserController@updateProfile')->name('users.updateProfile');

    Route::get('users/password/{user}', 'UserController@changePassword')->name('users.changePassword');

    Route::patch('users/password/{user}', 'UserController@postChangePassword')->name('users.postChangePassword');

    Route::patch('comments/approve/{comment}', 'CommentController@approve')->name('comments.approve');

    Route::patch('comments/disapprove/{comment}', 'CommentController@disapprove')->name('comments.disapprove');
    
    Route::resource('postviews', 'PostViewController');

    Route::delete('postviews-deleteall', 'PostViewController@deleteall')->name('postviews.deleteall');
    
    Route::resource('settings', 'SettingController');

    Route::resource('contactus', 'ContactUsController');

    Route::get('contactus/{contactus}/reply', 'ContactUsController@reply')->name('contactus.reply');

    Route::post('message/send', 'ChatController@send');
    
});

Route::post('comments/store', 'CommentController@store')->name('comments.store');
Route::post('comments/reply', 'CommentController@reply')->name('comments.reply');

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'FrontendController@index')->name('frontend.index');
// Route::get('/page/{menu}/', 'FrontendController@urlmapper')->name('frontend.urlmapper');
Route::get('{menuslug}', 'FrontendController@urlmapper')->name('frontend.urlmapper');

Route::get('posts/{slug}', 'FrontendController@showpost')->name('frontend.posts.show');

Route::get('posts/category/{slug}', 'FrontendController@showcategoryposts')->name('frontend.category.posts');

app/Slide.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slide extends Model
{
    protected $fillable = ['caption', 'subcaption', 'image', 'visibility', 'order'];
}

app/Http/Controllers/SlideController.php
<?php

namespace App\Http\Controllers;

use App\Slide;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class SlideController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $slides = Slide::orderBy('order')->get();
        return view('slides.index', compact('slides'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('slides.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validate
         $this->validate(request(), [
            'image'=>'required',
        ]);

        Slide::create([
            'caption'=>$request->caption,
            'subcaption'=>$request->subcaption,
            'image'=>$request->file('image')->storeAs('slides//', uniqid().'.'.$request->file('image')->getClientOriginalExtension(), 'public'),
            'visibility'=>$request->visibility,
            'order'=>$request->order,
        ]);

        return redirect()->route('slides.index')->with('success', 'Slide created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Slide  $slide
     * @return \Illuminate\Http\Response
     */
    public function show(Slide $slide)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Slide  $slide
     * @return \Illuminate\Http\Response
     */
    public function edit(Slide $slide)
    {
        return view('slides.edit', compact('slide'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Slide  $slide
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Slide $slide)
    {
        if ($request->file('image')!=null) {
            //Delete the former image.
            Storage::disk('public')->delete($slide->image);
        }

        $slide->update([
            'caption'=>$request->caption,
            'subcaption'=>$request->subcaption,
            'image'=>$request->file('image')==null? $slide->image :$request->file('image')->storeAs('slides//', uniqid().'.'.$request->file('image')->getClientOriginalExtension(), 'public'),
            'visibility'=>$request->visibility,
            'order'=>$request->order,
        ]);

        return redirect()->route('slides.index')->with('success', 'Slide updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Slide  $slide
     * @return \Illuminate\Http\Response
     */
    public function destroy(Slide $slide)
    {
        //Delete the image 
        Storage::disk('public')->delete($slide->image);

        $slide->delete();

        return redirect()->route('slides.index')->with('success', 'Slide deleted successfully');
    }
}

resources/views/slides/create.blade.php
@extends('layouts.dashboard')

@section('content')
    @include('partials.successmsg')
    @include('partials.errorbag')
    <section class="content-header">
        <h1>Add New Slide</h1> 
    </section>

    {{-- Main content --}}
    <section class="content">
        <div class="row">
            <div class="col-md-5">
                <div class="box">
                    <div class="box-header">
                        <div class="box-title">Add new slide</div>
                    </div>
                    <div class="box-body">
                        <form action="{{ route('slides.store') }}" method="post" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label>Caption</label>
                                <input type="text" name="caption" id="" class="form-control">
                            </div>

                            <div class="form-group">
                                <label>Subcaption</label>
                                <input type="text" name="subcaption" id="" class="form-control">
                            </div>

                            <div class="form-group">
                                <label>Add image</label>
                                <input type="file" name="image" id="">
                            </div>

                            <div class="form-group">
                                <label>Visibility (visible on home page)</label>
                                <input type="radio" name="visibility" value="1" checked> &nbsp; Visible &nbsp;
                                <input type="radio" name="visibility" value="0"> &nbsp; Hidden
                            </div>

                            <div class="form-group">
                                <label>Order</label>
                                <input type="number" name="order" class="form-control" min="1" value="1">
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-info">Add Slide</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/slides/edit.blade.php
@extends('layouts.dashboard')

@section('content')
    @include('partials.successmsg')
    @include('partials.errorbag')
    <section class="content-header">
        <h1>Edit Slide</h1> 
    </section>

    {{-- Main content --}}
    <section class="content">
        <div class="row">
            <div class="col-md-5">
                <div class="box">
                    <div class="box-body">
                        <form action="{{ route('slides.update', $slide->id) }}" method="post" enctype="multipart/form-data">
                            @csrf
                            @method('PATCH')
                            <div class="form-group">
                                <label>Caption</label>
                                <input type="text" name="caption" id="" class="form-control" value="{{$slide->caption}}">
                            </div>

                            <div class="form-group">
                                <label>Subcaption</label>
                                <input type="text" name="subcaption" id="" class="form-control" value="{{$slide->subcaption}}">
                            </div>

                            <div class="form-group">
                                <label>Add image</label>
                                <img src="{{ asset('storage/'.$slide->image) }}" width="100" class="img-rounded">
                                <input type="file" name="image" id="">
                            </div>

                            <div class="form-group">
                                <label>Visibility (visible on home page)</label>
                                <input type="radio" name="visibility" value="1" {{ $slide->visibility==1 ? 'checked' : '' }}> Visible &nbsp;
                                <input type="radio" name="visibility" value="0" {{ $slide->visibility==0 ? 'checked' : '' }}> Hidden
                            </div>

                            <div class="form-group">
                                <label>Order</label>
                                <input type="number" name="order" class="form-control" min="1" value="{{$slide->order}}">
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-info">Update Slide</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/slides/index.blade.php
@extends('layouts.dashboard')

@section('content')
    @include('partials.successmsg')

    <section class="content-header">
        <h1>Slides <a href="{{route('slides.create')}}" class="btn btn-info">Add New</a></h1> 
    </section>

    {{-- Main content --}}
    <section class="content">
        <div class="box">
            <div class="box-body">
                <div class="table-responsive">
                    <table id="example1" class="table table-bordered table-striped table-responsive">
                        <thead>
                            <tr>
                                <th><input type="checkbox" name="" id=""></th>
                                <th>Image</th>
                                <th>Caption</th>
                                <th>Visibility</th>
                                <th>Order</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($slides as $slide)
                                <tr>
                                    <td><input type="checkbox" name="" id=""></td>
                                    <td>
                                        <img src="{{ asset('storage/'.$slide->image) }}" width="100" class="img-rounded">
                                    </td>
                                    <td>{{ $slide->caption }}</td>
                                    <td>{{ $slide->visibility }}</td>
                                    <td>{{ $slide->order }}</td>
                                    <td>
                                        <a href="{{ route('slides.edit', $slide->id) }}" class="btn btn-success"><i class="fa fa-pencil"></i></a>
                                    </td>
                                    <td>
                                        <form id="deleteForm" method="post" action="{{ route('slides.destroy', $slide->id) }}">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger" onClick='return confirm("Are you sure you want to delete?")'><i class="fa fa-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
@endsection