routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/create-symlink', function () {
    Artisan::call('storage:link');
});

Route::get('/migratefresh', function () {
    Artisan::call('migrate:fresh');
});

Route::get('/seeder', function(){
    Artisan::call('db:seed');
});

Route::get('/down', function(){
    Artisan::call('down');
});

// Route::get('/up', function(){
//     Artisan::call('up');
// });


Auth::routes();

Route::prefix('admin')->middleware('auth')->group(function(){
    //You must be logged in to access this route
    Route::get('/index', 'AdminController@index')->name('admin.index');

    Route::resource('pages', 'PageController');

    Route::resource('categories', 'CategoryController');

    Route::resource('slides', 'SlideController');

    Route::resource('posts', 'PostController');
    
    Route::resource('menus', 'MenuController');

    Route::resource('comments', 'CommentController', ['except'=>['store']]);

    Route::resource('users', 'UserController');

    Route::get('users/profile/{user}', 'UserController@profile')->name('users.profile');

    Route::patch('users/profile/{user}', 'UserController@updateProfile')->name('users.updateProfile');

    Route::get('users/password/{user}', 'UserController@changePassword')->name('users.changePassword');

    Route::patch('users/password/{user}', 'UserController@postChangePassword')->name('users.postChangePassword');

    Route::patch('comments/approve/{comment}', 'CommentController@approve')->name('comments.approve');

    Route::patch('comments/disapprove/{comment}', 'CommentController@disapprove')->name('comments.disapprove');
    
    Route::resource('postviews', 'PostViewController');

    Route::delete('postviews-deleteall', 'PostViewController@deleteall')->name('postviews.deleteall');
    
    Route::resource('settings', 'SettingController');

    Route::resource('contactus', 'ContactUsController');

    Route::get('contactus/{contactus}/reply', 'ContactUsController@reply')->name('contactus.reply');

    Route::post('message/send', 'ChatController@send');
    
});

Route::post('comments/store', 'CommentController@store')->name('comments.store');
Route::post('comments/reply', 'CommentController@reply')->name('comments.reply');

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'FrontendController@index')->name('frontend.index');
// Route::get('/page/{menu}/', 'FrontendController@urlmapper')->name('frontend.urlmapper');
Route::get('{menuslug}', 'FrontendController@urlmapper')->name('frontend.urlmapper');

Route::get('posts/{slug}', 'FrontendController@showpost')->name('frontend.posts.show');

Route::get('posts/category/{slug}', 'FrontendController@showcategoryposts')->name('frontend.category.posts');

resources/views/pages/create.blade.php
@extends('layouts.dashboard')

@section('styles')
    <link href="{{asset('summernote/dist/summernote.css')}}" rel="stylesheet">
    <link href="{{asset('css/bootstrap-datetimepicker.min.css')}}" rel="stylesheet">
@endsection

@section('content')
    @include('partials.errorbag')
    @include('partials.successmsg')

    <section class="content-header">
        <h1>Add New Page</h1>
    </section>

    {{-- Main content --}}
    <section class="content">
        <form action="{{ route('pages.store') }}" method="post">
            @csrf
            <div class="row">
                <div class="col-md-8">
                    <div class="form-group">
                        <label for="">Page Title</label>
                        <input type="text" name="title" id="" class="form-control" required placeholder="Title">
                    </div>
                    <div class="form-group">
                        <label for="">SEO Description (optional)</label>
                        <input type="text" name="seo_description" id="" class="form-control" placeholder="SEO Description (optional)">
                    </div>
                    <div class="form-group">
                        <label for="">Page Content</label>
                        <textarea name="content" class="summernote" id="summernote"></textarea>
                    </div>
                    <br>
                    <p style="font-style: italic">For Developers...</p>
                    <div class="form-group">
                        <label for="">Style Sheet</label> <br>
                        <textarea name="styles" id="styles" cols="110" rows="30"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="">JavaScript</label> <br>
                        <textarea name="javascript" id="javascript" cols="110" rows="30"></textarea>
                    </div>
                </div>

                {{-- Second column --}}
                <div class="col-md-4">
                    <div class="box box-info">
                        <div class="box-header">
                            <h4>Publish</h4>
                        </div>

                        <div class="box-body">
                            <div class="form-group">
                                <button class="btn btn-default">Save Draft</button>
                                <button class="btn btn-default pull-right">Preview</button>
                            </div>
                            <br>

                            <div class="form-group">
                                <i class="fa fa-info-circle"></i> <label for="">Status: </label>
                                <select name="status" id="" class="form-control">
                                    <option value="draft">Draft</option>
                                    <option value="published">Published</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <i class="fa fa-eye"></i> <label for="">Visibility: </label>
                                <select name="visibility" id="" class="form-control">
                                    <option value="private">Private</option>
                                    <option value="public">Public</option>
                                    <option value="published">Published</option>
                                </select>
                            </div>
                        </div>
                        
                        <div class="box-footer">
                            <div class="form-group">
                                <button type="submit" class="btn btn-info pull-right">Publish</button>
                            </div>
                        </div>
                    </div>

                </div>
            </div>      
        </form>
    </section>
@endsection

@section('scripts')
    <script src="{{asset('summernote/dist/summernote.js')}}"></script>
    <script src="{{asset('js/moment.js')}}"></script>
    <script src="{{asset('js/bootstrap-datetimepicker.min.js')}}"></script>

    <script>
        $(document).ready(function() {
            $('#summernote').summernote({
                height:450,
                placeholder: 'Page content'
            });
        });
    </script>
@endsection

resources/views/pages/edit.blade.php
@extends('layouts.dashboard')

@section('styles')
    <link href="{{asset('summernote/dist/summernote.css')}}" rel="stylesheet">
@endsection


@section('content')
    @include('partials.errorbag')
    @include('partials.successmsg')
    <section class="content-header">
        <h1>Edit page</h1>
    </section>

    {{-- Main content --}}
    <section class="content">
        <form action="{{ route('pages.update', $page->id) }}" method="post">
            @csrf
            @method('PATCH')
            <div class="row">
                <div class="col-md-8">
                    <div class="form-group">
                        <label for="">Page Title</label>
                        <input type="text" name="title" id="" class="form-control" required value="{{$page->title}}" placeholder="Title">
                    </div>
                    <div class="form-group">
                        <label for="">SEO Description (optional)</label>
                        <input type="text" name="seo_description" id="" class="form-control" value="{{$page->seo_description}}" placeholder="SEO Description (optional)">
                    </div>
                    <div class="form-group">
                        <label for="">Page Content</label>
                        <textarea name="content" class="summernote" id="summernote">{{$page->content}}</textarea>
                    </div>
                    <br>
                    <p style="font-style: italic">For Developers...</p>
                    <div class="form-group">
                        <label for="">Style Sheet</label> <br>
                        <textarea name="styles" id="styles" cols="110" rows="30">{{$page->styles}}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="">JavaScript</label> <br>
                        <textarea name="javascript" id="javascript" cols="110" rows="30">{{$page->javascript}}</textarea>
                    </div>
                </div>

                {{-- Second column --}}
                <div class="col-md-4">
                    <div class="box box-info">
                        <div class="box-header">
                            <h4>Publish</h4>
                        </div>

                        <div class="box-body">
                            <div class="form-group">
                                <button class="btn btn-default">Save Draft</button>
                                <button class="btn btn-default pull-right">Preview</button>
                            </div>
                            <br>

                            <div class="form-group">
                                <i class="fa fa-info-circle"></i> <label for="">Status: </label>
                                <select name="status" id="" class="form-control">
                                    <option value="draft" {{ $page->status=='draft'?'selected':'' }}>Draft</option>
                                    <option value="published" {{ $page->status=='published'?'selected':'' }} >Published</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <i class="fa fa-eye"></i> <label for="">Visibility: </label>
                                <select name="visibility" id="" class="form-control">
                                    <option value="private" {{ $page->visibility=='private'?'selected':'' }}>Private</option>
                                    <option value="public" {{ $page->visibility=='public'?'selected':'' }} >Public</option>
                                    <option value="published" {{ $page->visibility=='published'?'selected':'' }} >Published</option>
                                </select>
                            </div>
                        </div>
                        
                        <div class="box-footer">
                            <button type="submit" class="btn btn-info pull-right">Update</button>
                        </div>
                    </div>

                </div>
            </div>      
        </form>
    </section>
@endsection

@section('scripts')
    <script src="{{asset('summernote/dist/summernote.js')}}"></script>

    <script>
        $(document).ready(function() {
            $('#summernote').summernote({
                height:450,
                placeholder: 'Page content'
            });
        });
    </script>
@endsection

resources/views/pages/index.blade.php
@extends('layouts.dashboard')

@section('styles')
    @include('partials.datatableStyles')
@endsection

@section('content')
    @include('partials.successmsg')
    <section class="content-header">
        <h1>Pages <a href="{{route('pages.create')}}" class="btn btn-info">Add New</a></h1> 
    </section>

    {{-- Main content --}}
    <section class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="table-responsive">
                    <table id="example1" class="table table-bordered table-striped table-responsive">
                        <thead>
                            <tr>
                                <th><input type="checkbox" name="" id=""></th>
                                <th>Title</th>
                                <th>Author</th>
                                <th>Status</th>
                                <th>Date</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($pages as $page)
                                <tr>
                                    <td><input type="checkbox" name="" id=""></td>
                                    <td>
                                        <a href="{{ route('pages.edit', $page->id) }}">{{ $page->title }}</a> 
                                    </td>
                                    <td>{{ $page->user->firstname ?? $page->user->username }} {{ $page->user->lastname }}</td>
                                    <td>{{ ucfirst($page->status) }}</td>
                                    <td>Published {{ $page->created_at->diffForHumans() }}</td>
                                    <td>
                                        <a href="{{ route('pages.edit', $page->id) }}" class="btn btn-success"><i class="fa fa-pencil"></i></a>
                                    </td>
                                    <td>
                                        <form id="deleteForm" method="post" action="{{ route('pages.destroy', $page->id) }}">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger" onClick='return confirm("Are you sure you want to delete this page?")'><i class="fa fa-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('scripts')
    @include('partials.datatableScripts')
@endsection